contracts/oracle/nodes/ChainlinkNode.sol
contracts/oracle/test/MockChainlinkAggregator.sol
test/oracle/nodes/ChainlinkNode.test.ts

fix: chainlink node twap 

---

contracts/hub/AccountManager.sol
contracts/hub/interfaces/IAccountManager.sol
test/hub/AccountManager.test.ts

feat: can override existing invite

---

contracts/hub/logic/HubPoolLogic.sol
test/hub/HubPool.test.ts

fix: don't increase total deposits by interest in repay with collateral

---

contracts/bridge/WormholeCCTPAdapter.sol
contracts/bridge/WormholeDataAdapter.sol
contracts/bridge/test/MockWormhole.sol
test/bridge/WormholeCCTPAdapter.test.ts
test/bridge/WormholeDataAdapter.test.ts

fix: consider womrhole publish message fee

---

contracts/hub/libraries/MathUtils.sol
contracts/hub/logic/HubPoolLogic.sol
contracts/hub/logic/LiquidationLogic.sol
test/hub/HubPool.test.ts
test/hub/utils/formulae.ts

fix: round in protocol favour in to f amount

---

contracts/oracle/nodes/StalenessCircuitBreakerNode.sol
test/oracle/nodes/StalenessCircuitBreakerNode.test.ts

fix: staleness check on node ts>block ts

---

contracts/bridge/BridgeRouter.sol
test/bridge/BridgeRouter.test.ts
test/utils/messages/messages.ts

feat: reduce gas consumption for failed messages 

---

contracts/bridge/CCIPDataAdapter.sol
contracts/bridge/CCIPTokenAdapter.sol
contracts/bridge/HubAdapter.sol
contracts/bridge/WormholeCCTPAdapter.sol
contracts/bridge/WormholeDataAdapter.sol
contracts/hub/AccountManager.sol
contracts/hub/HubCircleTokenPool.sol
contracts/hub/HubNonBridgedTokenPool.sol
contracts/hub/HubPool.sol
contracts/hub/LoanManager.sol
contracts/hub/SpokeManager.sol
contracts/hub/interfaces/IAccountManager.sol
contracts/hub/test/MockAccountManager.sol
contracts/spoke/RateLimited.sol
test/hub/AccountManager.test.ts

fix: cannot delete account

---

contracts/bridge/BridgeRouter.sol
test/bridge/BridgeRouter.test.ts

fix: cannot add zero address adapter

---

contracts/bridge/BridgeRouter.sol
test/bridge/BridgeRouter.test.ts

fix: check adapter address matches to handle id 0

---

contracts/oracle/modules/NodeManager.sol
contracts/oracle/nodes/PriceDeviationCircuitBreakerNode.sol
contracts/oracle/nodes/PriceDeviationSameOracleCircuitBreakerNode.sol
test/oracle/nodes/PriceDeviationCircuitBreakerNode.test.ts
test/oracle/nodes/PriceDeviationSameOracleCircuitBreakerNode.test.ts

fix: price dev (same oracle) node

---

contracts/hub/LoanManager.sol
contracts/hub/interfaces/ILoanManager.sol
contracts/hub/test/MockLoanManager.sol
test/hub/LoanManager.test.ts

fix: make rebalance permissioned

---

contracts/hub/AccountManager.sol
contracts/hub/Hub.sol
contracts/hub/LoanManager.sol
contracts/hub/interfaces/IAccountManager.sol
contracts/hub/interfaces/ILoanManager.sol
contracts/hub/test/MockAccountManager.sol
contracts/hub/test/MockLoanManager.sol
contracts/spoke/SpokeCommon.sol
contracts/spoke/SpokeToken.sol
test/hub/AccountManager.test.ts
test/hub/Hub.test.ts
test/hub/LoanManager.test.ts
test/spoke/SpokeCommon.test.ts
test/spoke/SpokeToken.test.ts
test/utils/bytes.ts

fix: frontun protection for create account and create loan

---

contracts/hub/logic/UserLoanLogic.sol

fix: delete collaterals and borrows mappings

---

contracts/hub/logic/HubPoolLogic.sol
test/hub/HubPool.test.ts

fix: check available liquidity when borrowing

---

contracts/hub/logic/UserLoanLogic.sol
test/hub/LoanManager.test.ts

fix: handle zero deposits and zero borrows

---

contracts/hub/libraries/MathUtils.sol
test/hub/utils/formulae.ts

fix: round in protocol favour for avg stable rate

---

contracts/bridge/BridgeMessenger.sol
contracts/bridge/BridgeRouter.sol
contracts/bridge/test/BridgeMessengerReceiver.sol
contracts/bridge/test/BridgeMessengerSender.sol
contracts/bridge/test/BridgeRouterReceiver.sol
contracts/hub/Hub.sol
contracts/hub/test/MockAccountManager.sol
contracts/spoke/SpokeCommon.sol
contracts/spoke/SpokeToken.sol
test/bridge/BridgeMessenger.test.ts
test/bridge/BridgeRouter.test.ts
test/hub/Hub.test.ts
test/spoke/SpokeCommon.test.ts
test/spoke/SpokeToken.test.ts

fix: permissioned retry + reverse and can override return message params

---

contracts/hub/LoanManager.sol
contracts/hub/logic/LoanManagerLogic.sol
test/hub/LoanManager.test.ts

fix: check loan is over-collateralised in switch borrow type 

---

contracts/hub/logic/HubPoolLogic.sol
test/hub/HubPool.test.ts
test/hub/libraries/MathUtils.test.ts
test/hub/utils/formulae.ts

fix: outdated deposit interest rate

---

contracts/oracle/nodes/PythNode.sol
test/oracle/nodes/PythNode.test.ts
test/oracle/utils/utils.ts

fix: pyth expo

---

contracts/oracle/nodes/ChainlinkNode.sol
contracts/oracle/test/MockChainlinkAggregator.sol
test/oracle/nodes/ChainlinkNode.test.ts
test/oracle/utils/nodeManagerUtils.ts

fix: chainlink node decimals 

---

contracts/hub/logic/LiquidationLogic.sol

fix: cannot mix borrows when liquidating

---

contracts/hub/logic/LoanManagerLogic.sol
test/hub/LoanManager.test.ts

fix: cannot rebalance up to to lower stable rate

---

contracts/hub/logic/LiquidationLogic.sol
test/hub/LoanManager.test.ts

fix: reduce collateral used in loan type by liquidation fee

---

contracts/hub/logic/UserLoanLogic.sol
test/hub/LoanManager.test.ts

fix: stable borrow balance increases 

---

contracts/hub/libraries/MathUtils.sol
test/hub/utils/formulae.ts

fix: scale down repay borrow amount by liquidation bonus 

---

contracts/hub/HubPool.sol
contracts/hub/interfaces/IHubPool.sol
contracts/hub/logic/HubPoolLogic.sol
contracts/hub/logic/LoanManagerLogic.sol
contracts/hub/test/HubPoolLogged.sol
contracts/hub/test/MockHubPool.sol
test/hub/HubPool.test.ts
test/hub/LoanManager.test.ts

fix: check available liquidity when withdrawing

---

contracts/hub/HubPool.sol
contracts/hub/logic/HubPoolLogic.sol
test/hub/HubPool.test.ts

fix: include excess and consider fee claim in total deposits 

---

contracts/oracle/nodes/ChainlinkNode.sol

fix: remove redundant break claue in chainlink node 

---

contracts/hub/HubPool.sol
contracts/hub/interfaces/IHubPool.sol
contracts/hub/logic/HubPoolLogic.sol
contracts/hub/test/MockHubPool.sol
test/hub/HubPool.test.ts

update indexes and rates on clear token fees 

---

contracts/hub/HubPool.sol
contracts/hub/interfaces/IHubPool.sol
contracts/hub/libraries/DataTypes.sol
contracts/hub/libraries/MathUtils.sol
contracts/hub/logic/HubPoolLogic.sol
contracts/hub/logic/LiquidationLogic.sol
contracts/hub/logic/LoanManagerLogic.sol
contracts/hub/logic/UserLoanLogic.sol
contracts/hub/test/MockHubPool.sol
test/hub/HubPool.test.ts
test/hub/LoanManager.test.ts
test/hub/utils/formulae.ts

fix: calculation of average stable borrow interest rate

---

contracts/oracle/nodes/VaultAssetToSharesNode.sol
contracts/oracle/test/MockTokenizedVaultStandard.sol
test/oracle/nodes/VaultAssetToSharesNode.test.ts
test/oracle/utils/nodeManagerUtils.ts

Added `VaultAssetToSharesNode` node as `ExternalNode`

feat: vault asset to shares node
